        /usr
            mark
                book
                    ch1.r
                    ch2.r
                    ch3.r
                course
                    cop3530
                        fall05
                            syl.r
                        spr06
                            syl.r
                        sum06
                            syl.r
                junk
            alex
                junk
            bill
                work
                course
                    cop3212
                        fall05
                            grades
                            prog1.r
                            prog2.r
                        fall06
                            prog2.r
                            prog1.r
                            grades
