            ch1.r            3
            ch2.r            2
            ch3.r            4
        book                10
                    syl.r    1
                fall05       2
                    syl.r    5
                spr06        6
                    syl.r    2
                sum06        3
            cop3530         12
        course              13
        junk                 6
    mark                    30
        junk                 8
    alex                     9
        work                 1
                    grades   3
                    prog1.r  4
                    prog2.r  1
                fall05       9
                    prog2.r  2
                    prog1.r  7
                    grades   9
                fall06      19
            cop3212         29
        course              30
    bill                    32
/usr                        72
